lab3/lab3/Models/DictViewModel.cs
using System.Text;
using System.Text.Json;
using lab3.Database;

namespace lab3.Models;
using System.Text.Json.Serialization;

public class DictViewModel
{
    // public SortedDictionary<int, Record> PhoneDictionary;
    // public SortedDictionary<string, string>? ReadFromFile()
    // {
    //     using (var fs = new FileStream("./Data/Dict.json", FileMode.OpenOrCreate))
    //     {
    //         SortedDictionary<string, string>? dict = JsonSerializer.Deserialize<SortedDictionary<string, string>>(fs);
    //
    //         if (dict != null)
    //         {
    //             return dict;
    //         }
    //         else return null;
    //     }
    // }

    // public bool WriteToFile()
    // {
    //     File.Delete("./Data/Dict.json");
    //     using (var fs = new FileStream("./Data/Dict.json", FileMode.OpenOrCreate))
    //     {
    //         var json = JsonSerializer.Serialize(PhoneDictionary);
    //         fs.Write(new ReadOnlySpan<byte>(UnicodeEncoding.UTF8.GetBytes(json)));
    //         return true;
    //     }
    // }
    public SortedDictionary<int, Record> GetDictionary()
    {
        using (var db = new ApplicationContext())
        {
            return new SortedDictionary<int, Record>
                (db.Records.ToDictionary(k=>k.Id, l=>l));
        }
    }
    public SortedDictionary<int, Record> ReadFromDatabase()
    {
        using (ApplicationContext db = new ApplicationContext())
        {
            return new SortedDictionary<int, Record>
                (db.Records.ToDictionary(i => i.Id, r => r));
        }
    }

    public void WriteToDatabase(Record record)
    {
        using (ApplicationContext db = new ApplicationContext())
        {
            db.Records.Add(record);
            db.SaveChanges();
        }
    }

    public void Add(string name, string number)
    {
        WriteToDatabase(new Record(name, number));
    }

    public bool Remove(int id)
    {
        using (var db = new ApplicationContext())
        {
            var rec = db.Records.Find(id);
            if (rec == null) return false;
            db.Remove(rec);
            db.SaveChanges();
            return true;
        }
    }

    public bool Update(int id, string name, string number)
    {
        using (var db = new ApplicationContext())
        {
            var rec = db.Records.Find(id);
            if (rec is null) return false;
            rec.Name = name;
            rec.Number = number;
            db.SaveChanges();
            return true;
        }
    }
    
}

lab3/lab3/Models/ErrorViewModel.cs
namespace lab3.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

lab3/lab3/Models/Record.cs
namespace lab3.Models;

public class Record
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Number { get; set; }

    public Record(string name, string number)
    {
        Name = name;
        Number = number;
    }
}

lab3/lab3/Controllers/DictController.cs
using lab3.Models;
using Microsoft.AspNetCore.Mvc;

namespace lab3.Controllers;

public class DictController : Controller
{
    private DictViewModel model = new DictViewModel();
    
    [HttpGet]
    public IActionResult Index()
    {
        return View(model);
    }

    [HttpPost]
    public IActionResult AddSave(string name, string number)
    {
        model.Add(name, number);
        return View(model);
       
    }

    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Update(int? id, string name, string number)
    {
        if (id is null) return View();
        ViewBag.Id = id;
        ViewBag.Name = name;
        ViewBag.Number = number;
        return View();
    }

    [HttpPost]
    public IActionResult UpdateSave(int? id, string? name, string? number)
    {
        if (id is null || name is null || number is null)
        {
            ViewBag.resText = "Запись не найдена";
            return View();
        }
        model.Update((int)id, name, number);
        ViewBag.resText = "Запись успешно обновлена";
        return View();
    }

    [HttpGet]
    public IActionResult Delete(int? id)
    {
        if (id is null) return View();
        ViewData["id"] = id;
        return View();
    }

    [HttpPost]
    public IActionResult DeleteSave(int id)
    {
        model.Remove(id);
        return View();
    }
    
}

lab3/lab3/Controllers/HomeController.cs
using System.Diagnostics;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using lab3.Models;

namespace lab3.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    

    // public string Index (Dictionary<string,string> items)
    // {
    //     string result = "";
    //     foreach (var item in items)
    //     {
    //         result = $"{result} {item.Key} - {item.Value}; ";
    //     }
    //     return result ;
    // }
    
    public IActionResult Index()
    {
        return View();
    }

   
    protected internal string Hello() => "hello asp net";
    
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

lab3/lab3/Views/Dict/Add.cshtml
@{
    ViewBag.Title = "Добавление новой записи";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<form action="AddSave" method="post" class="d-flex flex-column w-25">
    <label>Имя</label>
    <input type="text" name="name"/>
    <label>Номер телефона</label>
    <input type="number" name="number"/>
    <br/>
    <input type="submit" value="Добавить" class="btn btn-outline-success"/>
</form>

lab3/lab3/Views/Dict/AddSave.cshtml
@model DictViewModel
@{
    Layout = "_Layout";
}

<div>
    <h1>
        Запись была успешно добавлена
    </h1>
     <a asp-action="Index" asp-controller="Dict">Вернуться к справочнику</a>
</div>

lab3/lab3/Views/Dict/Delete.cshtml
@{
    ViewBag.Title = "Удалить запись";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<form action="/Dict/DeleteSave" method="post" class="d-flex flex-column w-25">
    <label>Удалить запись с данным ID?</label>
    <input type="number" name="id" value="@ViewData["id"]"/>
    <br/>
    <input type="submit" class="btn btn-outline-success" value="Подтвердить"/>
</form>

lab3/lab3/Views/Dict/DeleteSave.cshtml
@{
    ViewBag.Title = "Удаление записи";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h1>Запись успешно удалена</h1>

lab3/lab3/Views/Dict/Index.cshtml
@model DictViewModel

@{
    ViewData["Title"] = "Dictionary";
    Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Phone Dictionary</h1>
    <h2>Count: @Model.GetDictionary().Count</h2>
    <a asp-action="Add" class="btn btn-outline-dark">Добавить новую запись</a>
    <a asp-action="Update" class="btn btn-outline-dark">Изменить запись</a>
    <a asp-action="Delete" class="btn btn-outline-dark">Удалить запись</a>
    <ul class="text-sm-start">
        @foreach(var person in Model.GetDictionary())
        {
            <li>@person.Value.Name - @person.Value.Number 
                <button>
                    <a href="/Dict/Delete/@person.Key">
                        удалить
                    </a>
                </button>
                <button>
                    <a href="/Dict/Update?id=@person.Key&name=@person.Value.Name&number=@person.Value.Number">
                        изменить
                    </a>
                </button>
                </li>
        }
    </ul>
</div>

lab3/lab3/Views/Dict/Update.cshtml
@{
    ViewBag.Title = "Обновить запись";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<form action="/Dict/UpdateSave" method="post" class="d-flex flex-column w-25">
    <label>Обновить запись с текущим id:</label>
    <input type="number" name="id" value="@ViewBag.Id"/>
    <label>Новое Имя</label>
    <input type="text" name="name" value="@ViewBag.Name"/>
    <label>Новый номер</label>
    <input type="number" name="number" value="@ViewBag.Number"/>
    <br/>
    <input type="submit" value="Изменить" class="btn btn-outline-success"/>
</form>

lab3/lab3/Views/Dict/UpdateSave.cshtml
@{
    ViewBag.Title = "Изменение номера";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h1>@ViewBag.resText</h1>

lab3/lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

lab3/lab3/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

lab3/lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lab3.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab3</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dict" asp-action="Index">Dictionary</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>